# ATTENTION

# Transition config settings

# ReadConsistency is the consistency of the plot package
# WriteConsistency is the consistency of the collector package

# The keyspace package still uses the cassandraAdmin consistency
# and the udpError package still uses the cassandra consistency
# The idea is to change the cassandra gobol package to accept
# multiple consistencies and abstract that to the applications

# BE CAREFUL!!! There are, for now, FOUR consistency settings

ReadConsistency = [
  "quorum",
  "one"
]

WriteConsisteny = [
  "quorum",
  "one"
]

# MaxConcurrentTimeseries CANNOT BE BIGGER THAN MaxConcurrentReads
MaxConcurrentTimeseries = 10

MaxConcurrentReads = 20

MaxTimeseries = 50

LogQueryTSthreshold = 25

BoltPath = "/export/mycenae/cache.db"

MetaSaveInterval = "5s"

MaxConcurrentPoints	= 10000
MaxConcurrentBulks = 5
MaxMetaBulkSize = 1000000
MetaBufferSize = 1000000

[cassandra]
  keyspace = "macs"
  consistency = "quorum"
  nodes = [
      "d3-macs-stg-b1.host.intranet",
      "d3-macs-stg-b2.host.intranet",
      "d3-macs-stg-b3.host.intranet"  
]
  username = "ts_ws_admin"
  password = "ts_ws_admin"
  connections = 3
  discoverHosts = true
  discoverySleep = 10
  retry = 5
  pageSize = 5000
  timeout = "60s"
  protoVersion = 4

[TTL]
  max = 10

[UDPserver]
  port = "4242"
  readBuffer = 1048576

[HTTPserver]
  path = "/"
  port = "8080"
  bind = ""

[UDPserverV2]
  port = "4243"
  readBuffer = 1048576

[logs.general.file]
  writeTo = true
  [logs.general.file.settings]
    symlink = true
    logLevel = "INFO"
    rotationPeriod = "daily"
    timeFormat = "2006-01-02_15:04:03"
    path = "/export/logs/mycenae/mycenae.log"

[logs.stats.file]
  writeTo = true
  [logs.stats.file.settings]
    symlink = true
    logLevel = "INFO"
    rotationPeriod = "daily"
    timeFormat = "2006-01-02_15:04:03"
    path = "/export/logs/mycenae/mycenae-stats.log"

[stats]
  address = "localhost"
  port = "4243"
  protocol = "udp"
  ksid = "ts_28aca8d1_c9f1_4499_a51a_174611fd9796"
  ttl = "5"
  interval = "@every 1m"
  [stats.tags]
    service = "mycenae"

[probe]
  threshold = 0.5

[elasticSearch]
  index = "ts"
  [elasticSearch.cluster]
    nodes = [
        "d3-macs-stg-b1.host.intranet:9200",
        "d3-macs-stg-b4.host.intranet:9200",
        "d3-macs-stg-b5.host.intranet:9200" 
    ]
    preferred = "d3-macs-stg-b1.host.intranet:9200"
    timeout = 5

[[services]]
  name = "mts"
  id = "mts-http"
  port = 8080
  tags = [
    "http"
  ]
  poolInterval = "5s"

[[services]]
  name = "mts"
  id = "mts-udpv1"
  port = 4242
  tags = [
    "udpv1"
  ]
  poolInterval = "5s"

[[services]]
  name = "mts"
  id = "mts-udpv2"
  port = 4243
  tags = [
    "udpv2"
  ]
  poolInterval = "5s"

[consul]
  address = "localhost.consul.macs.intranet:8501"
  scheme = "https"
  token = "1af67e4c-e0ee-efe3-4fff-29a7855aaed5"
  certFile = "/etc/opt/mycenae/ssl/agent.cert"
  keyFile = "/etc/opt/mycenae/ssl/agent.key"
  cafile = "/etc/opt/mycenae/ssl/ca.cert"

[HTTPCheck]
  name = "probe-mts"
  path = "http://localhost:8080/probe"
  interval = "5s"
