# ATTENTION

# Transition config settings

# ReadConsistency is the consistency of the plot package
# WriteConsistency is the consistency of the collector package

# The keyspace package still uses the cassandraAdmin consistency
# and the udpError package still uses the cassandra consistency
# The idea is to change the cassandra gobol package to accept
# multiple consistencies and abstract that to the applications

# Max number of timeseries allowed to be queried (Solr pagination)
MaxTimeseries = 50000

# Warning number of timeseries
LogQueryTSthreshold = 5000

# Max number of concurrent points being processed
MaxConcurrentPoints = 1000

# Max number of concurrent bulk requests to elasticsearch
MaxConcurrentBulks = 1

# Number, in bytes of bulk playload
MaxMetaBulkSize = 10000

# Number of points in buffer
MetaBufferSize = 100000

# Elastichseach batch of meta save interval
MetaSaveInterval = "1s"

# The default TTL to use if not specified
DefaultTTL = 1

# Tha max TTL allowed to be specified
MaxAllowedTTL = 90

# Defines the default pagination size used on solr if none was specified
DefaultPaginationSize = 1000

# Mandatory keysets to create on app startup
DefaultKeysets = ["pdeng_stats", "pdeng_collectd", "pdeng_analytics"]

# Allow Cross Origin Resource Sharing
AllowCORS = true

# All default keyspaces
[DefaultKeyspaces]
  one_day = 1
  three_days = 3
  one_week = 7
  two_weeks = 14
  one_month = 30
  three_months = 90

#The default keyspace data used to create all default keyspaces
[DefaultKeyspaceData]
  Datacenter = "dc_gt_a1"
  ReplicationFactor = 2
  Contact = "l-pd-engenharia@uolinc.com"

[cassandra]
  keyspace = "mycenae"
  consistency = "one"
  nodes = ["172.18.0.2","172.18.0.3","172.18.0.4"]
  username = "cassandra"
  password = "cassandra"
  connections = 3
  discoverHosts = true
  discoverySleep = 10
  retry = 5
  pageSize = 5000
  timeout = "60s"
  protoVersion = 4

[UDPserver]
  port = "4243"
  readBuffer = 1048576

[HTTPserver]
  path = "/"
  port = "8082"
  bind = "0.0.0.0"

[[NetdataHandlerReplacements]]
  LookForPropertyName   = "chart_type"
  LookForPropertyValue  = "^disk_.*"
  PropertyAsNewMetric   = "chart_type"
  NewTagName            = "volume"
  NewTagValue           = "chart_family"

[[NetdataHandlerReplacements]]
  LookForPropertyName   = "chart_type"
  LookForPropertyValue  = "^net_.*"
  PropertyAsNewMetric   = "chart_type"
  NewTagName            = "interface"
  NewTagValue           = "chart_family"

[[NetdataHandlerReplacements]]
  LookForPropertyName   = "chart_type"
  LookForPropertyValue  = "^net$"
  PropertyAsNewMetric   = "chart_type"
  NewTagName            = "interface"
  NewTagValue           = "chart_family"

[NetdataServer]
  port = 8023
  bind = "0.0.0.0"
  onErrorTimeout = 5 
  maxBufferSize = 1024

[TELNETserver]
  port = 443
  bind = "0.0.0.0"
  onErrorTimeout = 5 
  maxBufferSize = 204800

[logs]
  environment = "PROD"
  [logs.general]
    level = "DEBUG"
    prefix = "general"
  [logs.stats]
    level = "DEBUG"
    prefix = "stats"

[stats]
  address = "0.0.0.0"
  port = "8082"
  protocol = "http"
  httptimeout = "10s"
  httppostinterval = "1m"
  interval = "@every 1m"
  runtime = true
  [stats.tags]
    service = "mycenae"
    ttl = "1"
    ksid = "pdeng_stats"

[statsAnalytic]
  address = "0.0.0.0"
  port = "8082"
  protocol = "http"
  httptimeout = "10s"
  httppostinterval = "10m"
  interval = "@every 10m"
  runtime = false
  [statsAnalytic.tags]
	service = "mycenae"
	ttl = "1"
	ksid = "pdeng_analytics"

[probe]
  threshold = 0.5

[metadataSettings]
  numShards = 1
  replicationFactor = 1
  url = "http://172.18.0.6:8983/solr"
  IDCacheTTL = -1
  QueryCacheTTL = -1
  KeysetCacheTTL = -1
  MaxReturnedMetadata = 10000
  ZookeeperConfig = "mycenae"
  BlacklistedKeysets = ["chimera", "blacklist"]

[memcached]
  pool = ["172.18.0.10:11211","172.18.0.11:11211","172.18.0.12:11211"]
  timeout = 10000
  maxIdleConns = 5
