# ATTENTION

# Transition config settings

# ReadConsistency is the consistency of the plot package
# WriteConsistency is the consistency of the collector package

# The keyspace package still uses the cassandraAdmin consistency
# and the udpError package still uses the cassandra consistency
# The idea is to change the cassandra gobol package to accept
# multiple consistencies and abstract that to the applications

# MaxConcurrentTimeseries CANNOT BE BIGGER THAN MaxConcurrentReads
# Max number of concurrent timeseries being processed
MaxConcurrentTimeseries = 50

# Max number of concurrent read queries on cassandra
MaxConcurrentReads = 100

# Max number of timeseries allowed to be queried
MaxTimeseries = 5000

# Warning number of timeseries
LogQueryTSthreshold = 1000

# Max number of concurrent points being processed
MaxConcurrentPoints = 1000

# Max number of concurrent bulk requests to elasticsearch
MaxConcurrentBulks = 1

# Number, in bytes of bulk playload
MaxMetaBulkSize = 1000000

# Number of points in buffer
MetaBufferSize = 100000

# Elastichseach batch of meta save interval
MetaSaveInterval = "1s"

# The default TTL to use if not specified
DefaultTTL = 1

# Tha max TTL allowed to be specified
MaxAllowedTTL = 90

# The maximum number of results from the suggest api
MaxSuggestions = 25

# Mandatory keysets to create on app startup
DefaultKeysets = ["stats", "collectd"]

# Allow Cross Origin Resource Sharing
AllowCORS = true

# All default keyspaces
[DefaultKeyspaces]
  one_day = 1
  three_days = 3
  one_week = 7
  two_weeks = 14
  one_month = 30
  three_months = 90

#The default keyspace data used to create all default keyspaces
[DefaultKeyspaceData]
  Datacenter = "dc_gt_a1"
  ReplicationFactor = 2
  Contact = "l-pd-plat-servicos@uolinc.com"

[cassandra]
  keyspace = "mycenae"
  consistency = "one"
  nodes = ["172.17.0.3","172.17.0.4","172.17.0.5"]
  username = "cassandra"
  password = "cassandra"
  connections = 3
  discoverHosts = true
  discoverySleep = 10
  retry = 5
  pageSize = 5000
  timeout = "60s"
  protoVersion = 4

[UDPserver]
  port = "4242"
  readBuffer = 1048576

[UDPserverV2]
  port = "4243"
  readBuffer = 1048576

[HTTPserver]
  path = "/"
  port = "8080"
  bind = "0.0.0.0"

[logs]
  environment = "PROD"
  [logs.general]
    level = "INFO"
    prefix = "general"
  [logs.stats]
    level = "DEBUG"
    prefix = "stats"

[stats]
  address = "0.0.0.0"
  port = "4243"
  protocol = "udp"
  ksid = "stats"
  interval = "@every 1m"
  runtime = true
  [stats.tags]
    service = "mycenae"
    ttl = "7"
    ksid = "stats"

[probe]
  threshold = 0.5

[elasticSearch]
  index = "ts"
  [elasticSearch.cluster]
    type = "weighted"
    seed = "172.17.0.6:9200"
    limit = 1024
    timeout = 15

[memcached]
  pool = ["172.17.0.7:11211","172.17.0.8:11211","172.17.0.9:11211"]
  ttl = 3600
  maxIdleConns = 5
