# ATTENTION

# Transition config settings

# ReadConsistency is the consistency of the plot package
# WriteConsistency is the consistency of the collector package

# The keyspace package still uses the cassandraAdmin consistency
# and the udpError package still uses the cassandra consistency
# The idea is to change the cassandra gobol package to accept
# multiple consistencies and abstract that to the applications

# Max number of timeseries allowed to be queried (Solr pagination)
MaxTimeseries = 12000

# Warning number of timeseries
LogQueryTSthreshold = 5000

# Max number of concurrent points being processed
MaxConcurrentPoints = 1000

# Tha max TTL allowed to be specified
MaxAllowedTTL = 90

# Defines the default pagination size used on solr if none was specified
DefaultPaginationSize = 1000

# Mandatory keysets to create on app startup
DefaultKeysets = ["pdeng_validation_errors", "pdeng_stats", "pdeng_analytics", "pdeng_events"]

# Maximum size of bytes for each query processing
MaxBytesOnQueryProcessing = 1548576

# Allows these keysets to do queries with more than "MaxBytesOnQueryProcessing" bytes
UnlimitedQueryBytesKeysetWhiteList = ["pdeng_validation_errors", "pdeng_stats", "pdeng_analytics", "pdeng_events"]

# Silences all point validation errors from the logs
SilencePointValidationErrors = true

# Garbage collector initial percentage
GarbageCollectorPercentage = 75

# SHAKE hashing algorithm output size
TSIDKeySize = 16

# When starting up enables the automatic keyspace creation for the default keyspaces bellow
EnableAutoKeyspaceCreation = true

# Report metrics sent in the past (everything before the time bellow in miliseconds)
DelayedMetricsThreshold = 10000

# Defines the scylla tables clustering order 
ClusteringOrder = "DESC"

# All default keyspaces
[DefaultKeyspaces]
  one_day = 1
  three_days = 3
  one_week = 7

#The default keyspace data used to create all default keyspaces
[DefaultKeyspaceData]
  Datacenter = "dc_gt_a1"
  ReplicationFactor = 2
  Contact = "l-pd-engenharia@uolinc.com"

[cassandra]
  keyspace = "mycenae"
  consistency = "one"
  nodes = ["182.168.0.5","182.168.0.6","182.168.0.7"]
  username = "cassandra"
  password = "cassandra"
  connections = 3
  discoverHosts = true
  discoverySleep = 10
  retry = 5
  pageSize = 5000
  timeout = "60s"
  protoVersion = 4

[UDPserver]
  port = 4243
  readBuffer = 1048576

[HTTPserver]
  port = 8082
  bind = "loghost"
  EnableProfiling = false
  ForceErrorAsDebug = false
  AllowCORS = false

[TelnetManagerConfiguration]
  # The maximum request time to reach other nodes
  HTTPRequestTimeout = "120s"

  # The size of the connection close channel
  ConnectionCloseChannelSize = 10

  # The maximum telnet connections allowed per node
  MaxTelnetConnections = 10

  # The maximum number of unbalanced telnet connections
  MaxUnbalancedTelnetConnsPerNode = 2

  # the time duration to check if the node is balanced
  TelnetConnsBalanceCheckInterval = "10s"

  # the time duration to wait the unbalanced connection be dropped
  MaxWaitForDropTelnetConnsInterval = "35s"

  # the time duration to wait when a halt request is received for stop the balancing process
  MaxWaitForOtherNodeConnsBalancing = "35s"

  # the available timeseries nodes
  Nodes = ["mycenae1", "mycenae2"]

  # statistics collect timeout
  sendStatsTimeout = "10s"

[[NetdataServer]]
  port = 8023
  bind = "loghost"
  cacheDuration = "1m"
  maxIdleConnectionTimeout = "30s"
  maxBufferSize = 2048
  ServerName = "Netdata Telnet Server"
  SilenceLogs = true
  MultipleConnsAllowedHosts = ["127.0.0.1"]
  RemoveMultipleConnsRestriction = false

[[TELNETserver]]
  port = 8123
  bind = "loghost"
  maxIdleConnectionTimeout = "30s"
  maxBufferSize = 2048
  ServerName = "OpenTSDB Telnet Server 1"
  SilenceLogs = true
  MultipleConnsAllowedHosts = ["127.0.0.1"]
  RemoveMultipleConnsRestriction = false

[[TELNETserver]]
  port = 8223
  bind = "loghost"
  maxIdleConnectionTimeout = "30s"
  maxBufferSize = 2048
  ServerName = "OpenTSDB Telnet Server 2"
  SilenceLogs = true
  MultipleConnsAllowedHosts = ["127.0.0.1"]
  RemoveMultipleConnsRestriction = false

[logs]
  level = "debug"
  format = "console"

[stats]
  hashingAlgorithm = "shake128"
  hashSize = 10
  dataTTL = "1h"
  transportBufferSize = 512
  batchSendInterval = "60s"
  requestTimeout = "15s"
  serializerBufferSize = 2048
  debugInput = false
  debugOutput = false
  timeBetweenBatches = "100ms"
  printStackOnError = false
  pointValueBufferSize= 4096

  [stats.openTSDBTransports.opentsdb]
    readBufferSize = 64
    maxReadTimeout = "100ms"
    reconnectionTimeout = "3s"
    maxReconnectionRetries = 5
    disconnectAfterWrites = false

  [stats.httpTransports.number]
    serviceEndpoint = "/api/put"
    method = "PUT"
    expectedResponseStatus = 204
    timestampProperty = "timestamp"
    valueProperty = "value"
    [httpTransports.number.headers]
        "content-type" = "application/json"

  [[stats.backends]]
    addHostTag    = true
    cycleDuration = "15s"
    host          = "10.128.5.208"
    port          = 8082
    storage       = "normal"
    transport     = "number"

    [stats.backends.commonTags]
      ksid    = "pdeng_stats"
      service = "mycenae"
      ttl     = "14"

  [[stats.backends]]
    addHostTag    = true
    cycleDuration = "15s"
    host          = "10.128.5.208"
    port          = 8082
    storage       = "archive"
    transport     = "number"

    [stats.backends.commonTags]
      ksid    = "pdeng_analytics"
      service = "mycenae"
      ttl     = "365"

  [[stats.backends]]
    addHostTag    = false
    cycleDuration = "15s"
    host          = "loghost"
    port          = 8082
    storage       = "validation"
    transport     = "number"

    [stats.backends.commonTags]
      ksid    = "pdeng_validation_errors"
      service = "mycenae"
      ttl     = "1"

[metadataSettings]
  numShards = 1
  replicationFactor = 1
  url = "http://182.168.0.3:8983/solr"
  IDCacheTTL = -1
  QueryCacheTTL = -1
  MaxReturnedMetadata = 10000
  ZookeeperConfig = "mycenae"
  BlacklistedKeysets = ["chimera", "blacklist"]
  CacheKeyHashSize = 16
  KeysetCacheAutoUpdateInterval = "5m"
  [metadataSettings.queryClient]
    # the maximum number of simultaneous running requests
    MaxSimultaneousRequests = 2000
    # the maximum request time
    RequestTimeout = "2m"
    # enable/disable certificate validation check
    SkipCertificateValidation = true
  [metadataSettings.updateClient]
    # the maximum number of simultaneous running requests
    MaxSimultaneousRequests = 2000
    # the maximum request time
    RequestTimeout = "2m"
    # enable/disable certificate validation check
    SkipCertificateValidation = true

[memcached]
  # the nodes
  Nodes = ["182.168.0.9:11211","182.168.0.10:11211","182.168.0.11:11211"]
	
  # the number of idle connections per host
  NumConnectionsPerNode = 8

  # the time duration between connection retries
  ReconnectionTimeout = "1s"

  # the max time duration to wait a write operation
  MaxWriteTimeout = "3s"

  # the max time duration to wait a read operation
  MaxReadTimeout = "5s"

  # the maximum number of write retries
  MaxWriteRetries = 3

  # the size of the read buffer in bytes
  ReadBufferSize = 2048

  # activates the memcached metrics
  EnableMetrics = true

[validation]
  maxTextValueSize = 10000
  maxNumTags       = 20
  propertyRegexp   = "(?i)^[0-9a-z-\\._\\%\\&\\#\\;\\/]+$"
  keysetNameRegexp = "(?i)^[a-z_]{1}[a-z0-9_\\-]+[a-z0-9]{1}$"
  defaultTTL       = 1
  MaxPropertySize  = 256
