# ATTENTION

# Transition config settings

# ReadConsistency is the consistency of the plot package
# WriteConsistency is the consistency of the collector package

# The keyspace package still uses the cassandraAdmin consistency
# and the udpError package still uses the cassandra consistency
# The idea is to change the cassandra gobol package to accept
# multiple consistencies and abstract that to the applications

# Max number of timeseries allowed to be queried (Solr pagination)
MaxTimeseries = 50000

# Warning number of timeseries
LogQueryTSthreshold = 5000

# Max number of concurrent points being processed
MaxConcurrentPoints = 1000

# Tha max TTL allowed to be specified
MaxAllowedTTL = 90

# Defines the default pagination size used on solr if none was specified
DefaultPaginationSize = 1000

# Mandatory keysets to create on app startup
DefaultKeysets = ["pdeng_stats", "pdeng_collectd", "pdeng_analytics"]

# Maximum size of bytes for each query processing
MaxBytesOnQueryProcessing = 104857600

# Allows these keysets to do queries with more than "MaxBytesOnQueryProcessing" bytes
UnlimitedQueryBytesKeysetWhiteList = ["pdeng_stats", "pdeng_collectd", "pdeng_analytics"]

# Silences all point validation errors from the logs
SilencePointValidationErrors = false

# Garbage collector initial percentage
GarbageCollectorPercentage = 75

# SHAKE hashing algorithm output size
TSIDKeySize = 16

# When starting up enables the automatic keyspace creation for the default keyspaces bellow
EnableAutoKeyspaceCreation = true

# Report metrics sent in the past (everything before the time bellow in miliseconds)
DelayedMetricsThreshold = 3000

# All default keyspaces
[DefaultKeyspaces]
  one_day = 1
  three_days = 3
  one_week = 7
  two_weeks = 14
  one_month = 30
  three_months = 90

#The default keyspace data used to create all default keyspaces
[DefaultKeyspaceData]
  Datacenter = "dc_gt_a1"
  ReplicationFactor = 2
  Contact = "l-pd-engenharia@uolinc.com"

[cassandra]
  keyspace = "mycenae"
  consistency = "one"
  nodes = ["182.168.0.2","182.168.0.3","182.168.0.4"]
  username = "cassandra"
  password = "cassandra"
  connections = 3
  discoverHosts = true
  discoverySleep = 10
  retry = 5
  pageSize = 5000
  timeout = "60s"
  protoVersion = 4

[UDPserver]
  port = 4243
  readBuffer = 1048576

[HTTPserver]
  port = 8082
  bind = "localhost"
  EnableProfiling = false
  ForceErrorAsDebug = false
  AllowCORS = true

[GlobalTelnetServerConfiguration]
  # The maximum request time to reach other nodes
  HTTPRequestTimeout = "10s"

  # The size of the connection close channel
  ConnectionCloseChannelSize = 10

  # The maximum telnet connections allowed per node
  MaxTelnetConnections = 10

  # The maximum number of unbalanced telnet connections
  MaxUnbalancedTelnetConnsPerNode = 5

  # the time duration to check if the node is balanced
  TelnetConnsBalanceCheckInterval = "10s"

  # the time duration to wait the unbalanced connection be dropped
  MaxWaitForDropTelnetConnsInterval = "35s"

  # the time duration to wait when a halt request is received for stop the balancing process
  MaxWaitForOtherNodeConnsBalancing = "35s"

  # the available timeseries nodes
  Nodes = ["localhost"]

  # silence all info logs
  SilenceLogs = false

  # allows the listed host to connect multiple times
  MultipleConnsAllowedHosts = ["localhost"]

[NetdataServer]
  port = 8023
  bind = "localhost"
  onErrorTimeout = "5s"
  sendStatsTimeout = "10s"
  maxIdleConnectionTimeout = "3m"
  maxBufferSize = 2048
  cacheDuration = "1m"
  ServerName = "Netdata Telnet Server"

[TELNETserver]
  port = 8123
  bind = "localhost"
  onErrorTimeout = "5s" 
  sendStatsTimeout = "10s"
  maxIdleConnectionTimeout = "3m"
  maxBufferSize = 2048
  ServerName = "OpenTSDB Telnet Server"

[logs]
  level = "debug"
  format = "console"

[stats]
  hashingAlgorithm = "shake128"
  hashSize = 6
  transportBufferSize = 10000
  serializerBufferSize = 2048
  batchSendInterval = "30s"
  requestTimeout = "5s"
  maxReadTimeout = "100ms"
  reconnectionTimeout = "3s"
  dataTTL = "2m"
  readBufferSize = 64
  maxReconnectionRetries = 5
  #debugOutput = true
  #debugInput = true

  [[stats.backends]]
    host = "localhost"
    port = 8123
    type = "normal"
    cycleDuration = "15s"
    addHostTag = true
    [stats.backends.commonTags]
      service = "mycenae"
      ttl = "1"
      ksid = "pdeng_stats"

  [[stats.backends]]
    host = "localhost"
    port = 8123
    type = "archive"
    cycleDuration = "15s"
    addHostTag = true
    [stats.backends.commonTags]
      service = "mycenae"
      ttl = "1"
      ksid = "pdeng_stats"

[metadataSettings]
  numShards = 1
  replicationFactor = 1
  url = "http://182.168.0.6:8983/solr"
  IDCacheTTL = -1
  QueryCacheTTL = -1
  MaxReturnedMetadata = 10000
  ZookeeperConfig = "mycenae"
  BlacklistedKeysets = ["chimera", "blacklist"]
  CacheKeyHashSize = 16
  KeysetCacheAutoUpdateInterval = "5m"

[memcached]
  # the nodes
  Nodes = ["182.168.0.10:11211","182.168.0.11:11211","182.168.0.12:11211"]
	
  # the number of idle connections per host
  NumConnectionsPerNode = 5
  
  # the time duration between connection retries
	ReconnectionTimeout = "1s"

	# the max time duration to wait a write operation
	MaxWriteTimeout = "3s"

  # the max time duration to wait a read operation
	MaxReadTimeout = "100ms"

	# the maximum number of write retries
	MaxWriteRetries = 3

	# the size of the read buffer in bytes
	ReadBufferSize = 2048

  # activates the memcached metrics
  EnableMetrics = true

[validation]
  maxTextValueSize = 10000
	maxNumTags       = 20
	propertyRegexp   = "(?i)^[0-9a-z-\\._\\%\\&\\#\\;\\/]+$"
  keysetNameRegexp = "(?i)^[a-z_]{1}[a-z0-9_\\-]+[a-z0-9]{1}$"
	defaultTTL       = 1
  MaxPropertySize  = 64