# ATTENTION

# Transition config settings

# ReadConsistency is the consistency of the plot package
# WriteConsistency is the consistency of the collector package

# The keyspace package still uses the cassandraAdmin consistency
# and the udpError package still uses the cassandra consistency
# The idea is to change the cassandra gobol package to accept
# multiple consistencies and abstract that to the applications

# Max number of timeseries allowed to be queried (Solr pagination)
MaxTimeseries = 5000

# Warning number of timeseries
LogQueryTSthreshold = 5000

# Max number of concurrent points being processed
MaxConcurrentPoints = 1000

# Tha max TTL allowed to be specified
MaxAllowedTTL = 90

# Defines the default pagination size used on solr if none was specified
DefaultPaginationSize = 1000

# Mandatory keysets to create on app startup
DefaultKeysets = ["pdeng_stats", "pdeng_collectd", "pdeng_analytics"]

# Maximum size of bytes for each query processing
MaxBytesOnQueryProcessing = 1548576

# Allows these keysets to do queries with more than "MaxBytesOnQueryProcessing" bytes
UnlimitedQueryBytesKeysetWhiteList = ["pdeng_stats", "pdeng_collectd", "pdeng_analytics"]

# Silences all point validation errors from the logs
SilencePointValidationErrors = true

# Garbage collector initial percentage
GarbageCollectorPercentage = 75

# SHAKE hashing algorithm output size
TSIDKeySize = 16

# When starting up enables the automatic keyspace creation for the default keyspaces bellow
EnableAutoKeyspaceCreation = false

# All default keyspaces
[DefaultKeyspaces]
  one_day = 1
  three_days = 3
  one_week = 7
  two_weeks = 14
  one_month = 30
  three_months = 90

#The default keyspace data used to create all default keyspaces
[DefaultKeyspaceData]
  Datacenter = "dc_gt_a1"
  ReplicationFactor = 2
  Contact = "l-pd-engenharia@uolinc.com"

[cassandra]
  keyspace = "mycenae"
  consistency = "one"
  nodes = ["10.128.5.232", "10.128.5.233", "10.128.5.234", "10.128.5.235", "10.128.5.236", "10.128.5.237"]
  username = "cassandra"
  password = "cassandra"
  connections = 3
  discoverHosts = true
  discoverySleep = 10
  retry = 5
  pageSize = 5000
  timeout = "60s"
  protoVersion = 4

[UDPserver]
  port = 4243
  readBuffer = 1048576

[HTTPserver]
  port = 80
  bind = "0.0.0.0"
  EnableProfiling = false
  ForceErrorAsDebug = true
  AllowCORS = false 

[GlobalTelnetServerConfiguration]
  # The maximum request time to reach other nodes
  HTTPRequestTimeout = "10s"

  # The size of the connection close channel
  ConnectionCloseChannelSize = 2000

  # The maximum telnet connections allowed per node
  MaxTelnetConnections = 2000

  # The maximum number of unbalanced telnet connections
  MaxUnbalancedTelnetConnsPerNode = 50

  # the time duration to check if the node is balanced
  TelnetConnsBalanceCheckInterval = "5m"

  # the time duration to wait the unbalanced connection be dropped and in which telnet servers will not receive new connections
  MaxWaitForDropTelnetConnsInterval = "121s"

  # the time duration to wait when a halt request is received for stop the balancing process
  MaxWaitForOtherNodeConnsBalancing = "121s"

  # the available timeseries nodes
  Nodes = ["a1-heleno1", "a1-heleno2", "a1-heleno3"]

  # silence all info logs
  SilenceLogs = true

[NetdataServer]
  port = 8023
  bind = "loghost"
  onErrorTimeout = "10s"
  maxBufferSize = 102400
  sendStatsTimeout = "15s"
  maxIdleConnectionTimeout = "120s"
  cacheDuration = "10m"
  ServerName = "Netdata Telnet Server"

[TELNETserver]
  port = 8123
  bind = "loghost"
  onErrorTimeout = "10s"
  maxBufferSize = 102400
  sendStatsTimeout = "5s"
  maxIdleConnectionTimeout = "120s"
  ServerName = "OpenTSDB Telnet Server"

[logs]
  level = "error"
  format = "json"

[stats]
  address = "10.128.7.19"
  port = 80
  protocol = "http"
  httptimeout = "10s"
  httppostinterval = "1m"
  interval = "@every 1m"
  runtime = false
  [stats.tags]
    service = "mycenae"
    ttl = "14"
    ksid = "pdeng_stats"

[statsAnalytic]
  address = "10.128.7.19"
  port = 80
  protocol = "http"
  httptimeout = "10s"
  httppostinterval = "10m"
  interval = "@every 10m"
  runtime = false
  [statsAnalytic.tags]
    service = "mycenae"
    ttl = "365"
    ksid = "pdeng_analytics"

[metadataSettings] 
  numShards = 4
  replicationFactor = 1
  url = "http://10.128.7.28:8983/solr"
  IDCacheTTL = 7200
  QueryCacheTTL = 600
  KeysetCacheTTL = 600
  MaxReturnedMetadata = 10000
  ZookeeperConfig = "mycenae"
  BlacklistedKeysets = ["inventory"]
  CacheKeyHashSize = 16

[memcached]
  # the memcached node list
  Nodes =  ["182.168.0.4:11211","182.168.0.3:11211","182.168.0.2:11211"]

  # the number of idle connections per host
  NumConnectionsPerNode = 8

  # the time duration between connection retries
  ReconnectionTimeout = "1s"

  # the max time duration to wait a write operation
  MaxWriteTimeout = "3s"

  # the max time duration to wait a read operation
  MaxReadTimeout = "120s"

  # the maximum number of write retries
  MaxWriteRetries = 3

  # the size of the read buffer in bytes
  ReadBufferSize = 2048

[validation]
  maxTextValueSize = 10000
  maxNumTags       = 20
  propertyRegexp   = "^[0-9A-Za-z-\\._\\%\\&\\#\\;\\/]+$"
  keysetNameRegexp = "^[a-z_]{1}[a-z0-9_\\-]+[a-z0-9]{1}$"
  defaultTTL       = 1
  MaxPropertySize  = 256
